export const CUISINE_FILTERS = {
    African: "african",
    Chinese: "chinese",
    Japanese: "japanese",
    Korean: "korean",
    Vietnamese: "vietnamese",
    Thai: "thai",
    Indian: "indian",
    British: "british",
    Irish: "irish",
    French: "french",
    Italian: "italian",
    Mexican: "mexican",
    Spanish: "spanish",
    Middle_Eastern: "middle eastern",
    Jewish: "jewish",
    American: "american",
    Cajun: "cajun",
    Southern: "southern",
    Greek: "greek",
    German: "german",
    Nordic: "nordic",
    Eastern_European: "eastern european",
    Caribbean: "caribbean",
    Latin_American: "latin american",
  };
  
  export const DIET_FILTERS = {
    Pescetarian: "pescetarian",
    Vegan: "vegan",
    Vegetarian: "vegetarian",
    Paleo: "paleo",
    Primal: "primal",
  };
  
  export const INTOLERANCES_FILTERS = {
    Dairy: "dairy",
    Egg: "egg",
    Gluten: "gluten",
    Peanut: "peanut",
    Sesame: "sesame",
    Seafood: "seafood",
    Shellfish: "shellfish",
    Soy: "soy",
    Sulfite: "sulfite",
    TreeNut: "tree nut",
    Wheat: "wheat",
  };